-- +goose Up
ALTER TABLE members
    ADD COLUMN contact VARCHAR(100) UNIQUE NOT NULL,
    ADD COLUMN email VARCHAR(100) UNIQUE,
    ADD COLUMN password VARCHAR(255) NOT NULL,
    ADD COLUMN role VARCHAR(50) DEFAULT 'USER',
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN is_active BOOLEAN DEFAULT TRUE;

-- +goose Down
ALTER TABLE members
    DROP COLUMN contact,
    DROP COLUMN email,
    DROP COLUMN password,
    DROP COLUMN role,
    DROP COLUMN created_at,
    DROP COLUMN updated_at,
    DROP COLUMN is_active;
