# Config file for air (https://github.com/cosmtrek/air)

[build]
  # Command to build your app
  cmd = "go build -o ./tmp/main.exe ./cmd/main.go"
  # Binary to run after build
  bin = "./tmp/main.exe"
  # Watch these directories for changes
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  follow_symlink = true
  # Delay after the first build
  delay = 1000

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true

[debug]
  enable = false

[runner]
  # Pass arguments to the binary
  args = []
  # Working directory
  dir = "."
  # Environment variables
  env = ["GO_ENV=development"]
  # Forward signals
  forward = true
  # Graceful restart
  grace = 500
